# GIAO THỨC
CMD_NAME = "NAME"
CMD_MSG = "MSG"
CMD_SYSTEM = "SYS"
CMD_ROLE = "ROLE"
CMD_ACTION = "ACT"
CMD_INPUT_REQ = "INPUT"
CMD_PHASE = "PHASE"
CMD_OVER = "OVER"

# === DANH SÁCH ROLE ID ===

# Phe Sói
ROLE_WEREWOLF = "Werewolf"
ROLE_ALPHA_WOLF = "Alpha Wolf"       
ROLE_LEADER_WOLF = "Leader Wolf"     
ROLE_WOLF_CUB = "Wolf Cub"
ROLE_LONE_WOLF = "Lone Wolf"
ROLE_SORCERESS = "Sorceress"
ROLE_DIRE_WOLF = "Dire Wolf"
ROLE_VEGETARIAN_WOLF = "Vegetarian Wolf"
ROLE_WOLFMAN = "Wolfman"

# Phe Dân
ROLE_VILLAGER = "Villager"
ROLE_SEER = "Seer"
ROLE_BODYGUARD = "Bodyguard"
ROLE_HUNTER = "Hunter"
ROLE_WITCH = "Witch"
ROLE_CUPID = "Cupid"
ROLE_LYCAN = "Lycan"
ROLE_OLD_MAN = "Old Man"
ROLE_APPRENTICE_SEER = "Apprentice Seer"
ROLE_TOUGH_GUY = "Tough Guy"
ROLE_SICK_MAN = "Sick Man"
ROLE_PRINCE = "Prince"
ROLE_INSOMNIAC = "Insomniac"
ROLE_BEHOLDER = "Beholder"
ROLE_HUNTRESS = "Huntress"
ROLE_MENTALIST = "Mentalist"
ROLE_REVEALER = "Revealer"
ROLE_PRIEST = "Priest"
ROLE_DOPPELGANGER = "Doppelganger"
ROLE_DRUNK = "Drunk"
ROLE_DETECTIVE = "Detective"
ROLE_AURA_SEER = "Aura Seer"
ROLE_MAYOR = "Mayor"
ROLE_MARTYR = "Martyr"
ROLE_TWINS = "Twins"
ROLE_MYSTIC_SEER = "Mystic Seer"
ROLE_CURSED = "Cursed"
ROLE_LITTLE_GIRL = "Little Girl"
ROLE_GRANNY = "Granny"

# Phe 3
ROLE_TERRORIST = "Terrorist"
ROLE_TANNER = "Tanner"
ROLE_VAMPIRE = "Vampire"
ROLE_CULT_LEADER = "Cult Leader"
ROLE_HOODLUM = "Hoodlum"
ROLE_MUMMY = "Mummy"
ROLE_BLOODY_MARY = "Bloody Mary"
ROLE_CHUPACABRA = "Chupacabra"